I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 73, in script
    center "W  A  V  E  S"
Exception: Parameter 'interact' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 73, in script
    center "W  A  V  E  S"
  File "C:\Users\matthew\Downloads\RenPy\renpy-6.99.12.2-sdk\renpy\ast.py", line 613, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "C:\Users\matthew\Downloads\RenPy\renpy-6.99.12.2-sdk\renpy\exports.py", line 1142, in say
    who(what, interact=interact)
  File "C:\Users\matthew\Downloads\RenPy\renpy-6.99.12.2-sdk\renpy\atl.py", line 413, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'interact' is not known by ATL Transform.

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
waves '87: Business Cruizin' 1.0
